### ISSUE TITLE
GCP Secret Vault Error

### ISSUE THREAD

**Issue by shankinson** [abdolence/secret-vault-rs#100]
Loading secrets from GCP via metadata service is failing in gcloud-sdk 0.25.0 (https://github.com/abdolence/gcloud-sdk-rs/pull/154).

```
Failed to refresh secrets: NetworkError(SecretVaultNetworkError { public: SecretVaultErrorPublicGenericDetails { code: "Unknown" }, message: "status: Unknown, message: \"gce metadata service error: Error retrieving data from metadata server: 404 Not Found(Not Found\\n). URL: http://metadata.google.internal//computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform\", details: [], metadata: MetadataMap { headers: {} }" })
```

A fix was added to gcloud-sdk 0.25.2

**Comment by abdolence** [comment]
Hey, thanks for the PR. 
While I'm fine with merging it strictly speaking it is not necessary since people would need to update their Cargo.lock file anyway (either for gcloud or this crate).

**Comment by abdolence** [comment]
This is fixed in Google Cloud SDK crate v0.25.2. Anyone who bumps into it, please update your Cargo.lock file.

**Comment by shankinson** [comment]
> Hey, thanks for the PR. While I'm fine with merging it strictly speaking it is not necessary since people would need to update their Cargo.lock file anyway (either for gcloud or this crate).

This is why I opened the PR, because I had done a `cargo update` on our project after some code changes and wasn't sure why things stopped working. Spent hours looking at our code to realize it had nothing to do with our code.

Figured this would prevent someone else from spinning their wheels.

**Comment by abdolence** [comment]
Yes, definitely good to make it more visibile!

**Comment by yuankai-statsig** [comment]
> > Hey, thanks for the PR. While I'm fine with merging it strictly speaking it is not necessary since people would need to update their Cargo.lock file anyway (either for gcloud or this crate).
> 
> This is why I opened the PR, because I had done a `cargo update` on our project after some code changes and wasn't sure why things stopped working. Spent hours looking at our code to realize it had nothing to do with our code.
> 
> Figured this would prevent someone else from spinning their wheels.

Thanks for the visibility bump. I also was hit by this error and spent hours looking for fix.

**Comment by abdolence** [comment]
Sorry to hear this was disruptive for you. This whole thing is related to Hyper 1 (and related deps) upgrade, and hopefully now this kind of thing wouldn't happen for a while.
