### ISSUE TITLE
[GCP] Is there a way to use a credentials file?

### ISSUE THREAD

**Issue by chanced** [abdolence/secret-vault-rs#21]
Is there a way to use a credentials file with GCP? `GcpSecretManagerSourceOptions` just seems to accept a project ID, which is fine for staging / production but in dev, you need to be able to supply the credentials.

The [gcp_auth crate](https://docs.rs/gcp_auth/latest/gcp_auth/) ([repo](https://github.com/hrvolapeter/gcp_auth)) could be used to easily provide auth with gcp.

**Comment by chanced** [comment]
Ah, I apologize. I hadn't read the documentation for [gcloud-sdk](https://github.com/abdolence/gcloud-sdk-rs). I just need to set the `GOOGLE_APPLICATION_CREDENTIALS` env variable.

Thanks for the awesome work!

**Comment by abdolence** [comment]
> I just need to set the GOOGLE_APPLICATION_CREDENTIALS env variable.

@chanced that or you can use `gcloud auth application-default login`
